services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: nestboard
      POSTGRES_USER: nestboard
      POSTGRES_PASSWORD: nestboard
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestboard"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
